setwd("/Users/worshamn/Dropbox/Documents/Regis/MSDS650/week7/")
passing <- read.csv("nflpassing_names.csv",sep = '\t')
playernames <- passing[,1]
passing <- passing[,-1]
rownames(passing) <- playernames
#remove team and postition
passing <- passing[,-2]
passing <- passing[,-2]
head(passing)
km <-kmeans(passing[,1:17], 3, iter.max=1000, nstart=10000)
plot(passing[,17], passing[,6], col=km$cluster, xlab = 'rating',ylab = 'yards')
plot(passing[,17], passing[,4], col=km$cluster, xlab = 'rating',ylab = 'percentage')
plot(passing[,17], passing[,1], col=km$cluster, xlab = 'rating',ylab = 'ranking')
plot(passing[,17], passing[,3], col=km$cluster, xlab = 'rating',ylab = 'attempts')
plot(passing[,17], passing[,2], col=km$cluster, xlab = 'rating',ylab = 'completions')
plot(passing[,17], passing[,8], col=km$cluster, xlab = 'rating',ylab = 'yards per game')
plot(passing[,17], passing[,9], col=km$cluster, xlab = 'rating',ylab = 'touchdowns')
plot(passing[,17], passing[,10], col=km$cluster, xlab = 'rating',ylab = 'int')
plot(passing[,1], passing[,10], col=km$cluster, xlab = 'ranking',ylab = 'int')
plot(passing[,17], passing[,16], col=km$cluster, xlab = 'rating',ylab = 'sacks')
plot(passing[,9], passing[,16], col=km$cluster, xlab = 'touchdowns',ylab = 'sacks')
plot(passing[,1], passing[,16], col=km$cluster, xlab = 'ranking',ylab = 'sacks')
plot(passing[,10], passing[,16], col=km$cluster, xlab = 'int',ylab = 'sacks')
plot(passing[,1], passing[,9], col=km$cluster, xlab = 'ranking',ylab = 'touchdowns')
plot(passing[,1], passing[,13], col=km$cluster, xlab = 'ranking',ylab = 'long')
plot(passing[,1], passing[,11], col=km$cluster, xlab = 'ranking',ylab = 'firstdowns')
plot(passing[,17], passing[,11], col=km$cluster, xlab = 'rating',ylab = 'firstdowns')
plot(passing[,6], passing[,11], col=km$cluster, xlab = 'yards',ylab = 'firstdowns')
plot(passing[,9], passing[,11], col=km$cluster, xlab = 'touchdowns',ylab = 'firstdowns')
plot(passing[,16], passing[,11], col=km$cluster, xlab = 'sacks',ylab = 'firstdowns')
plot(passing[,10], passing[,11], col=km$cluster, xlab = 'int',ylab = 'firstdowns')
plot(passing[,10], passing[,4], col=km$cluster, xlab = 'int',ylab = 'compPct')
plot(passing[,1], passing[,4], col=km$cluster, xlab = 'ranking',ylab = 'compPct')
plot(passing[,17], passing[,4], col=km$cluster, xlab = 'rating',ylab = 'compPct')
plot(passing[,10], passing[,9], col=km$cluster, xlab = 'int',ylab = 'touchdowns')
newpassing <- data.frame(passing[,1:9],-passing[,10],passing[,11:15],-passing[,16],passing[,17])
head(newpassing)
km <-kmeans(newpassing[,1:17], 3, iter.max=1000, nstart=10000)
plot(newpassing[,17], newpassing[,6], col=km$cluster, xlab = 'rating',ylab = 'yards')
